//===- AMDISAAsmParser.cpp - AMD ISA Assembly Parser Implementation ------===//
//
// Implementation of AMD ISA Assembly Parser
//
// This parser reads AMD GCN ISA (.s) assembly lines and creates
// amdisa.inst ops inside an MLIR Module.
//
// Expected input:
//   v_add_f32 v1, v2, v3
//   s_waitcnt vmcnt(0)
//
// Output ops:
//   amdisa.inst { mnemonic = "...", operands = [...], raw_text = "..." }
//
//===----------------------------------------------------------------------===//

#include "AMDISAAsmParser.h"

#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/raw_ostream.h"

// AMDISA dialect operations
#include "mlir/Dialect/AMDISA/IR/AMDISAOps.h"

// Assembly parsing utilities
#include "parse_utils.h"
#include "AMDGCNAssembly.h"
#include "AMDGPUMetadata.h"
#include "ParsedProgram.h"

#include <iostream>

//===----------------------------------------------------------------------===//
// Helper Functions
//===----------------------------------------------------------------------===//

/// Convert argument properties to MLIR DictionaryAttr
/// This is used to encode kernel argument metadata from AMD GPU metadata
template <typename ArgT>
static mlir::DictionaryAttr
propsToDictAttr(mlir::OpBuilder &b, const ArgT &arg) {
  llvm::SmallVector<mlir::NamedAttribute> kvs;

  for (auto &p : arg.getAllProperties()) {
    llvm::StringRef k = p.first;
    llvm::StringRef v = p.second;

    // Convert numeric properties to integers
    if (k == "size" || k == "offset" || k == "align" ||
        k == "pointee_align") {
      int iv = 0;
      if (!v.getAsInteger(10, iv))
        kvs.emplace_back(b.getStringAttr(k),
                          b.getI32IntegerAttr(iv));
    } else {
      // Keep string properties as-is
      kvs.emplace_back(b.getStringAttr(k),
                        b.getStringAttr(v));
    }
  }

  return mlir::DictionaryAttr::get(b.getContext(), kvs);
}

namespace mlir::amdisa {

//===----------------------------------------------------------------------===//
// AMDISAAsmParser Implementation
//===----------------------------------------------------------------------===//

AMDISAAsmParser::AMDISAAsmParser(llvm::StringRef filename)
    : filename(filename) {}

mlir::OwningOpRef<mlir::ModuleOp>
AMDISAAsmParser::parseModule(mlir::MLIRContext &context) {

  mlir::OpBuilder builder(&context);
  auto module = mlir::ModuleOp::create(builder.getUnknownLoc());
  builder.setInsertionPointToEnd(module.getBody());

  // Parse the AMD GCN assembly file
  AMDGCNAssembly assembly = parseAMDGCNAssembly(filename.str());

  // Process each line of the assembly
  for (size_t lineNum = 1; lineNum <= assembly.getLineCount(); ++lineNum) {
    const LineInfo *line = assembly.getLine(lineNum);
    if (!line) continue;

    auto loc = builder.getUnknownLoc();

    switch (line->kind) {

      case LineKind::Label: {
        std::string labelName = line->labelName;
        
        // Extract pure label name (remove comment part)
        // Example: "vec_add: ; @vec_add" → "vec_add"
        llvm::StringRef labelRef(labelName);
        size_t colonPos = labelRef.find(':');
        if (colonPos != llvm::StringRef::npos) {
          labelRef = labelRef.substr(0, colonPos).trim();
        }
        std::string pureLabelName = labelRef.str();
        
        // 1. Skip .Lfunc_end labels (function end markers, generated by outer scope)
        if (pureLabelName.rfind(".Lfunc_end", 0) == 0) {
          break;
        }
        
        // 2. Skip labels with same name as kernel (function entry, generated by gpu.func)
        llvm::StringRef kname;
        if (auto a = module->getAttrOfType<mlir::StringAttr>("amdisa.kernel_name"))
          kname = a.getValue();
        if (!kname.empty() && pureLabelName == kname.str()) {
          break;
        }
        
        // 3. Keep all other labels (including .LBB0_X basic block labels)
        auto nameAttr = builder.getStringAttr(labelName);
        builder.create<LabelOp>(loc, nameAttr);
        break;
      }

    case LineKind::Instruction: {
      const ParsedInstruction &inst = *line->instruction;

      auto mnemonicAttr = builder.getStringAttr(inst.opcode);

      // Convert operands to array of string attributes
      llvm::SmallVector<mlir::Attribute> operandAttrs;
      operandAttrs.reserve(inst.operands.size());
      for (const auto &op : inst.operands) {
        operandAttrs.push_back(builder.getStringAttr(op.text));
      }

      auto opsAttr = builder.getArrayAttr(operandAttrs);
      auto rawAttr = builder.getStringAttr(inst.originalText);

      builder.create<InstOp>(loc, mnemonicAttr, opsAttr, rawAttr);
      break;
    }

    case LineKind::KernelName: {
      // .globl amdisa_kernel
      if (!module->hasAttr("amdisa.kernel_name")) {
        auto nameAttr = builder.getStringAttr(line->kernelName);
        module->setAttr("amdisa.kernel_name", nameAttr);
      }
      break;
    }

    case LineKind::AmdgcnTarget: {
      // .amdgcn_target "amdgcn-amd-amdhsa--gfx950"
      if (!module->hasAttr("llvm.target_triple")) {
        auto tripleAttr = builder.getStringAttr(line->amdgcnTarget);
        module->setAttr("llvm.target_triple", tripleAttr);
      }
      break;
    }

    case LineKind::AmdhsaCodeObjectVersion: {
      if (!module->hasAttr("amdgpu.code_object_version")) {
        int version = 0;

        if (!line->amdhsaCodeObjectVersion.empty()) {
          version = std::stoi(line->amdhsaCodeObjectVersion);
        }

        auto verAttr = builder.getI32IntegerAttr(version);
        module->setAttr("amdgpu.code_object_version", verAttr);
      }
      break;
    }

    case LineKind::Directive:
      // Skip generic directives
      break;

    case LineKind::Comment:
      // Skip comments
      break;

    case LineKind::Metadata:
      // Metadata is processed separately below
      break;

    case LineKind::Unknown:
    default:
      // Skip unknown lines
      break;
    }
  }

  // Process AMD GPU metadata (kernel arguments, register usage, etc.)
  if (assembly.hasMetadata()) {
    const AMDGPUMetadata &meta = assembly.getMetadata();

    llvm::StringRef kname;
    if (auto a = module->getAttrOfType<mlir::StringAttr>("amdisa.kernel_name"))
      kname = a.getValue();

    llvm::SmallVector<mlir::Attribute> argDicts;

    for (const auto &k : meta.kernels) {
      if (!kname.empty() && (k.symbol == kname.str() || k.name == kname.str())) {
        argDicts.reserve(k.args.size());
        for (const auto &arg : k.args) {
          // Include ALL parameters (including hidden ones)
          // Hidden parameters are required for correct kernarg_segment_size
          argDicts.push_back(propsToDictAttr(builder, arg));
        }

        // Store register counts as module attributes
        module->setAttr("amdisa.sgpr_count", builder.getI32IntegerAttr(k.sgprCount));
        module->setAttr("amdisa.vgpr_count", builder.getI32IntegerAttr(k.vgprCount));
        module->setAttr("amdisa.agpr_count", builder.getI32IntegerAttr(k.agprCount));
        
        // Store kernarg_segment_size for validation
        module->setAttr("amdisa.kernarg_segment_size", builder.getI32IntegerAttr(k.kernargSegmentSize));
        
        break;
      }
    }

    // Store kernel arguments metadata
    if (!argDicts.empty())
      module->setAttr("amdisa.kernargs", builder.getArrayAttr(argDicts));
  }

  return module;
}

} // namespace mlir::amdisa

