cmake -G Ninja ../llvm \
  -DLLVM_ENABLE_PROJECTS="clang;mlir;lld" \
  -DLLVM_TARGETS_TO_BUILD="AMDGPU;X86" \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DMLIR_ENABLE_GPU=ON \
  -DMLIR_ENABLE_ROCM_CONVERSIONS=ON \
  -DMLIR_ENABLE_ROCM_RUNNER=ON \
  -DMLIR_INCLUDE_INTEGRATION_TESTS=ON \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo
