// ============================================================================
// Auto-generated by sp3_host_gen.py from FMOE_INT8_G1U1_1TG_4W_32mx1_128nx4.sp3
// This is a standalone HIP test driver for debugging gpu.printf output.
//
// Compile: hipcc --offload-arch=gfx942 -O0 -g FMOE_INT8_G1U1_1TG_4W_32mx1_128nx4_test.cpp -o test_kernel
// Run:     ./test_kernel --hsaco <path> --kernel <symbol> [options]
// ============================================================================
#include <hip/hip_runtime.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <cstdint>
#include <string>
#include <vector>

#define HIP_CHECK(cmd) do { \
    hipError_t err = (cmd); \
    if (err != hipSuccess) { \
        fprintf(stderr, "HIP error %d (%s) at %s:%d\n", \
                (int)err, hipGetErrorString(err), __FILE__, __LINE__); \
        exit(1); \
    } \
} while(0)

static void print_usage(const char *prog) {
    fprintf(stderr,
        "Usage: %s --hsaco <path> --kernel <symbol> [options]\n"
        "Options:\n"
        "  --hsaco <path>     Path to HSACO file (required)\n"
        "  --kernel <symbol>  Kernel symbol name (required)\n"
        "  --dim <N>          dim value (default: 7168)\n"
        "  --hidden-dim <N>   hidden_dim value (default: 2048)\n"
        "  --batch <N>        Batch/token count (default: 64)\n"
        "  --topk <N>         topk value (default: 8)\n"
        "  --eprt <N>         Expert count (default: 128)\n"
        "  --buf-size <MB>    Fallback buffer size in MB (default: 64)\n"
        "  --device <N>       GPU device index (default: 0)\n"
        "  --help             Show this help\n",
        prog);
}

int main(int argc, char **argv) {
    // ---- CLI argument parsing ----
    std::string hsaco_path;
    std::string kernel_sym;
    int dim        = 7168;
    int hidden_dim = 2048;
    int batch      = 64;
    int topk       = 8;
    int eprt       = 128;
    int buf_size_mb = 64;
    int device_id  = 0;

    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "--hsaco"      && i+1 < argc) { hsaco_path  = argv[++i]; }
        else if (arg == "--kernel"     && i+1 < argc) { kernel_sym  = argv[++i]; }
        else if (arg == "--dim"        && i+1 < argc) { dim         = atoi(argv[++i]); }
        else if (arg == "--hidden-dim" && i+1 < argc) { hidden_dim  = atoi(argv[++i]); }
        else if (arg == "--batch"      && i+1 < argc) { batch       = atoi(argv[++i]); }
        else if (arg == "--topk"       && i+1 < argc) { topk        = atoi(argv[++i]); }
        else if (arg == "--eprt"       && i+1 < argc) { eprt        = atoi(argv[++i]); }
        else if (arg == "--buf-size"   && i+1 < argc) { buf_size_mb = atoi(argv[++i]); }
        else if (arg == "--device"     && i+1 < argc) { device_id   = atoi(argv[++i]); }
        else if (arg == "--help") { print_usage(argv[0]); return 0; }
        else { fprintf(stderr, "Unknown arg: %s\n", argv[i]); print_usage(argv[0]); return 1; }
    }

    if (hsaco_path.empty() || kernel_sym.empty()) {
        fprintf(stderr, "Error: --hsaco and --kernel are required.\n");
        print_usage(argv[0]);
        return 1;
    }

    printf("=== SP3 Host Test Driver ===\n");
    printf("HSACO      : %s\n", hsaco_path.c_str());
    printf("Kernel     : %s\n", kernel_sym.c_str());
    printf("dim        : %d\n", dim);
    printf("hidden_dim : %d\n", hidden_dim);
    printf("batch      : %d\n", batch);
    printf("topk       : %d\n", topk);
    printf("eprt       : %d\n", eprt);
    printf("buf_size   : %d MB\n", buf_size_mb);
    printf("device     : %d\n", device_id);


    // ---- SP3 Constants ----
    const int SUB_X  = 32;
    const int SUB_GU = 512;
    const int Bpp    = 1;        // bytes per point
    const int DO_UP  = 1;      // G1U1 vs G1U0

    // ---- Derived dimensions ----
    const int u1_factor = (DO_UP == 1) ? 2 : 1;  // GU combined if u1


    // ---- MoE routing data (uniform round-robin for testing) ----
    // STP: sorted_token_ids  -- which token each slot maps to
    // SW:  sorted_weights    -- weight for each slot
    // SEP: sorted_expert_ids -- expert-id for each sub_X group

    int total_tokens = batch * topk;
    int sz_stp = total_tokens + eprt * SUB_X - topk;  // max length
    if (sz_stp < total_tokens) sz_stp = total_tokens;
    int sz_sw  = sz_stp;
    int sz_sep = (sz_stp + SUB_X - 1) / SUB_X;  // max groups
    int sub_X_cnt = sz_sep;   // for grid dim calculation

    // Allocate host routing arrays
    std::vector<uint32_t> h_stp(sz_stp, 0);
    std::vector<float>    h_sw(sz_sw, 1.0f);
    std::vector<uint32_t> h_sep(sz_sep, 0);

    // Round-robin assignment: token i -> expert (i % eprt)
    // Group tokens by expert in sub_X-sized chunks
    {
        int slot = 0;
        int group = 0;
        for (int e = 0; e < eprt && group < sz_sep; e++) {
            h_sep[group] = e;
            int tokens_for_expert = 0;
            for (int t = 0; t < batch; t++) {
                for (int k = 0; k < topk; k++) {
                    int token_expert = (t * topk + k) % eprt;
                    if (token_expert == e && slot < sz_stp) {
                        h_stp[slot] = t;
                        h_sw[slot]  = 1.0f;
                        slot++;
                        tokens_for_expert++;
                    }
                }
            }
            // Pad to SUB_X boundary with dummy token ids
            while (tokens_for_expert % SUB_X != 0 && slot < sz_stp) {
                h_stp[slot] = batch;  // out-of-range token (safe: will read zeros)
                h_sw[slot]  = 0.0f;
                slot++;
                tokens_for_expert++;
            }
            group += tokens_for_expert / SUB_X;
        }
        sub_X_cnt = group;  // actual number of groups
        printf("sub_X_cnt  : %d (routing groups)\n", sub_X_cnt);
    }


    // ---- HIP setup & buffer allocation ----
    HIP_CHECK(hipSetDevice(device_id));

    hipModule_t   module;
    hipFunction_t kernel_func;
    HIP_CHECK(hipModuleLoad(&module, hsaco_path.c_str()));
    HIP_CHECK(hipModuleGetFunction(&kernel_func, module, kernel_sym.c_str()));
    printf("Kernel loaded successfully.\n");

    size_t fallback_buf = (size_t)buf_size_mb * 1024 * 1024;


    // R: R address
    void *dev_R = nullptr;
    {
        size_t sz = (size_t)batch * dim * 2;
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_R, sz));
        HIP_CHECK(hipMemset(dev_R, 0, sz));
        printf("R                   : %p  (%zu bytes)\n", dev_R, sz);
    }

    // X: X address
    void *dev_X = nullptr;
    {
        size_t sz = (size_t)batch * dim * Bpp;
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_X, sz));
        HIP_CHECK(hipMemset(dev_X, 0, sz));
        printf("X                   : %p  (%zu bytes)\n", dev_X, sz);
    }

    // G: G address
    void *dev_G = nullptr;
    {
        size_t sz = (size_t)eprt * hidden_dim * dim * Bpp;
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_G, sz));
        HIP_CHECK(hipMemset(dev_G, 0, sz));
        printf("G                   : %p  (%zu bytes)\n", dev_G, sz);
    }

    // Xc: get buffer XC address--reserved
    void *dev_Xc = nullptr;
    {
        size_t sz = fallback_buf;
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_Xc, sz));
        HIP_CHECK(hipMemset(dev_Xc, 0, sz));
        printf("Xc                  : %p  (%zu bytes)\n", dev_Xc, sz);
    }

    // D: D address
    void *dev_D = nullptr;
    {
        size_t sz = (size_t)eprt * dim * hidden_dim * Bpp;
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_D, sz));
        HIP_CHECK(hipMemset(dev_D, 0, sz));
        printf("D                   : %p  (%zu bytes)\n", dev_D, sz);
    }

    // XQ: get buffer X-quant address
    void *dev_XQ = nullptr;
    {
        size_t sz = fallback_buf;
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_XQ, sz));
        HIP_CHECK(hipMemset(dev_XQ, 0, sz));
        printf("XQ                  : %p  (%zu bytes)\n", dev_XQ, sz);
    }

    // GQ: get buffer G-quant address
    void *dev_GQ = nullptr;
    {
        size_t sz = fallback_buf;
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_GQ, sz));
        HIP_CHECK(hipMemset(dev_GQ, 0, sz));
        printf("GQ                  : %p  (%zu bytes)\n", dev_GQ, sz);
    }

    // DQ: get buffer D-quant address
    void *dev_DQ = nullptr;
    {
        size_t sz = fallback_buf;
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_DQ, sz));
        HIP_CHECK(hipMemset(dev_DQ, 0, sz));
        printf("DQ                  : %p  (%zu bytes)\n", dev_DQ, sz);
    }

    // GsmQ: get buffer smooth quant address
    void *dev_GsmQ = nullptr;
    {
        size_t sz = fallback_buf;
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_GsmQ, sz));
        HIP_CHECK(hipMemset(dev_GsmQ, 0, sz));
        printf("GsmQ                : %p  (%zu bytes)\n", dev_GsmQ, sz);
    }

    // STP: STP address
    void *dev_STP = nullptr;
    {
        size_t sz = (size_t)sz_stp * sizeof(uint32_t);
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_STP, sz));
        HIP_CHECK(hipMemset(dev_STP, 0, sz));
        printf("STP                 : %p  (%zu bytes)\n", dev_STP, sz);
    }

    // SW: SW  address
    void *dev_SW = nullptr;
    {
        size_t sz = (size_t)sz_sw * sizeof(float);
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_SW, sz));
        HIP_CHECK(hipMemset(dev_SW, 0, sz));
        printf("SW                  : %p  (%zu bytes)\n", dev_SW, sz);
    }

    // SEP: SEP address
    void *dev_SEP = nullptr;
    {
        size_t sz = (size_t)sz_sep * sizeof(uint32_t);
        if (sz == 0) sz = fallback_buf;
        HIP_CHECK(hipMalloc(&dev_SEP, sz));
        HIP_CHECK(hipMemset(dev_SEP, 0, sz));
        printf("SEP                 : %p  (%zu bytes)\n", dev_SEP, sz);
    }

    // Upload routing data
    if (dev_STP && sz_stp > 0)
        HIP_CHECK(hipMemcpy(dev_STP, h_stp.data(), sz_stp * sizeof(uint32_t), hipMemcpyHostToDevice));
    if (dev_SW && sz_sw > 0)
        HIP_CHECK(hipMemcpy(dev_SW, h_sw.data(), sz_sw * sizeof(float), hipMemcpyHostToDevice));
    if (dev_SEP && sz_sep > 0)
        HIP_CHECK(hipMemcpy(dev_SEP, h_sep.data(), sub_X_cnt * sizeof(uint32_t), hipMemcpyHostToDevice));


    // ---- Kernarg buffer assembly ----
    // Each parameter slot is 0x10 (16 bytes) wide.
    // Total kernarg size: 0x190 (400 bytes)
    uint8_t kernarg[400];
    memset(kernarg, 0, sizeof(kernarg));

    // Compute stride values
    int stride_X          = dim * Bpp;
    int stride_GU         = dim * Bpp;
    int stride_D          = hidden_dim * Bpp;
    int stride_R          = dim * 2;  // bf16 output
    int stride_expert_GU  = stride_GU * hidden_dim * u1_factor;
    int stride_expert_D   = stride_D * dim;

    *(void**)(kernarg + 0x0) = dev_R;  // R (R address)
    *(void**)(kernarg + 0x10) = dev_X;  // X (X address)
    *(void**)(kernarg + 0x20) = dev_G;  // G (G address)
    *(void**)(kernarg + 0x30) = dev_Xc;  // Xc (get buffer XC address--reserved)
    *(void**)(kernarg + 0x40) = dev_D;  // D (D address)
    *(void**)(kernarg + 0x50) = dev_XQ;  // XQ (get buffer X-quant address)
    *(void**)(kernarg + 0x60) = dev_GQ;  // GQ (get buffer G-quant address)
    *(void**)(kernarg + 0x70) = dev_DQ;  // DQ (get buffer D-quant address)
    *(void**)(kernarg + 0x80) = dev_GsmQ;  // GsmQ (get buffer smooth quant address)
    *(void**)(kernarg + 0x90) = dev_STP;  // STP (STP address)
    *(void**)(kernarg + 0xA0) = dev_SW;  // SW (SW  address)
    *(void**)(kernarg + 0xB0) = dev_SEP;  // SEP (SEP address)

    *(uint32_t*)(kernarg + 0xC0) = (uint32_t)dim;  // dim (dim_size)
    *(uint32_t*)(kernarg + 0xD0) = (uint32_t)hidden_dim;  // hidden_dim (hidden_dim size)
    *(uint32_t*)(kernarg + 0xE0) = (uint32_t)batch * topk;  // token_cnt (get   token cnt)
    *(uint32_t*)(kernarg + 0xF0) = (uint32_t)eprt;  // eprt_cnt (get   expert cnt)
    *(uint32_t*)(kernarg + 0x100) = (uint32_t)stride_X;  // stride_X (one token size of X (in bytes))
    *(uint32_t*)(kernarg + 0x110) = (uint32_t)stride_GU;  // stride_GU (one token size of GU (in bytes))
    *(uint32_t*)(kernarg + 0x120) = (uint32_t)stride_D;  // stride_D (hidden-dim dimension size of D (in bytes))
    *(uint32_t*)(kernarg + 0x130) = (uint32_t)stride_R;  // stride_R (one token size of R(in bytes))
    *(uint32_t*)(kernarg + 0x140) = (uint32_t)stride_expert_GU;  // stride_expert_GU (one expert size of GU (in bytes))
    *(uint32_t*)(kernarg + 0x150) = (uint32_t)stride_expert_D;  // stride_expert_D (one expert size of D (in bytes))
    *(uint32_t*)(kernarg + 0x160) = (uint32_t)0;  // eGUQs (get   one expert GU-quant stride in bytes)
    *(uint32_t*)(kernarg + 0x170) = (uint32_t)0;  // eDQs (get   one expert D-quant stride in bytes)
    *(uint32_t*)(kernarg + 0x180) = (uint32_t)0;  // eGsmQs (get   one expert smooth-quant stride in bytes)

    // ---- Kernel launch ----
    int gdx = (hidden_dim/SUB_GU);
    int gdy = sub_X_cnt;
    int gdz = 1;
    int bdx = 256;
    int bdy = 1;
    int bdz = 1;

    if (gdx <= 0) gdx = 1;
    if (gdy <= 0) gdy = 1;
    if (gdz <= 0) gdz = 1;

    printf("Grid  : (%d, %d, %d)\n", gdx, gdy, gdz);
    printf("Block : (%d, %d, %d)\n", bdx, bdy, bdz);

    size_t arg_size = sizeof(kernarg);
    void *config[] = {
        HIP_LAUNCH_PARAM_BUFFER_POINTER, kernarg,
        HIP_LAUNCH_PARAM_BUFFER_SIZE,    &arg_size,
        HIP_LAUNCH_PARAM_END
    };

    printf("Launching kernel...\n");
    fflush(stdout);
    fflush(stderr);

    HIP_CHECK(hipModuleLaunchKernel(
        kernel_func,
        gdx, gdy, gdz,
        bdx, bdy, bdz,
        0,        // shared mem
        nullptr,  // stream (default)
        nullptr,  // kernel params (using config instead)
        (void **)&config
    ));

    HIP_CHECK(hipDeviceSynchronize());
    printf("Kernel completed.\n");
    fflush(stdout);
    fflush(stderr);


    // ---- Cleanup ----
    if (dev_R) (void)hipFree(dev_R);
    if (dev_X) (void)hipFree(dev_X);
    if (dev_G) (void)hipFree(dev_G);
    if (dev_Xc) (void)hipFree(dev_Xc);
    if (dev_D) (void)hipFree(dev_D);
    if (dev_XQ) (void)hipFree(dev_XQ);
    if (dev_GQ) (void)hipFree(dev_GQ);
    if (dev_DQ) (void)hipFree(dev_DQ);
    if (dev_GsmQ) (void)hipFree(dev_GsmQ);
    if (dev_STP) (void)hipFree(dev_STP);
    if (dev_SW) (void)hipFree(dev_SW);
    if (dev_SEP) (void)hipFree(dev_SEP);
    (void)hipModuleUnload(module);
    printf("Done.\n");
    return 0;
}
